# Generated by Django 3.0.1 on 2020-10-28 02:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uui', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name_plural': 'Bodegas',
            },
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uui', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Clasificaciones',
            },
        ),
        migrations.CreateModel(
            name='ConsejoPopular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uui', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Consejos Populares',
            },
        ),
        migrations.CreateModel(
            name='Notificacion_general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uui', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('mensaje', models.TextField(max_length=250, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uui', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uui', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Operaciones',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uui', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name_plural': 'Unidades de Medidas',
            },
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uui', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('image', models.ImageField(default='static/users/userDefault1.png', null=True, upload_to='static/users', verbose_name='Avatar')),
                ('referUser', models.UUIDField(null=True)),
                ('fa2', models.BooleanField(default=False, verbose_name='2FA')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uui', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('consejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodegaApp.ConsejoPopular', verbose_name='Consejo Popular')),
            ],
            options={
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='SeccionOperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uui', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodegaApp.TipoOperacion', verbose_name='Tipo de Operación')),
            ],
            options={
                'verbose_name_plural': 'Sección de operaciones',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uui', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('codigo', models.CharField(max_length=100, null=True, verbose_name='Código')),
                ('precio_venta', models.FloatField(verbose_name='Precio de Venta')),
                ('precio_costo', models.FloatField(verbose_name='Precio de Costo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodegaApp.Clasificacion', verbose_name='Clasificación')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodegaApp.UnidadMedida', verbose_name='Unidad de Medidas')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('imp_pv', models.FloatField(blank=True, default=0, verbose_name='Imp/PV')),
                ('imp_pc', models.FloatField(blank=True, default=0, verbose_name='Imp/PC')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodegaApp.Bodega', verbose_name='Bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodegaApp.Producto', verbose_name='Producto')),
                ('seccion_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodegaApp.SeccionOperacion', verbose_name='Sección de Operación')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uui', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodegaApp.Provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.AddField(
            model_name='consejopopular',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodegaApp.Municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='productos',
            field=models.ManyToManyField(to='BodegaApp.Producto', verbose_name='Productos'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodegaApp.Zona', verbose_name='Zona'),
        ),
    ]
