# Generated by Django 2.1.8 on 2020-11-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BodegaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='fa2',
        ),
        migrations.RemoveField(
            model_name='userapp',
            name='referUser',
        ),
    ]
